#!/bin/bash

# Create a bin directory
makeBinDir() {
  if [[ ! -d "./bin" ]]
  then
    mkdir bin
    echo "bin directory created"
  fi
}

if [[ "$1" =~ ^.*\.(cpp)$ ]]
then
    makeBinDir
    g++ -Wall -Werror -Wextra -Wno-unused-parameter -Wno-unused-variable -pedantic -lstdc++ -o "./bin/${1%.*}" "$1"
elif [[ -d "./src" ]]
then
  makeBinDir
  # gcc -pedantic -lstdc++ -o "./bin/main" "./src/main.cpp"
  g++ -Wall -Werror -Wextra -Wno-unused-parameter -Wno-unused-variable -pedantic -lstdc++ -o "./bin/main" "./src/main.cpp"
  ./bin/main
elif [[ ! -d "./src" ]]
then
    echo "No src directory found"
elif [[ ! -f "./src/main.cpp" ]]
then
    echo "No main.c file found"
else
    echo "Something went wrong"
fi